# .github/workflows/ci.yml

name: CI

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Choose the Python version you're using

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

